# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant payé')),
                ('date_paiement', models.DateField(verbose_name='date du paiement')),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte bancaire')], default='ESPECES', max_length=15, verbose_name='mode de paiement')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='observation')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('UNIQUE', 'Frais unique')], default='MENSUEL', max_length=12, verbose_name='périodicité')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academic.anneescolaire', verbose_name='année scolaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='academic.niveau', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'frais de scolarité',
                'verbose_name_plural': 'frais de scolarité',
                'ordering': ['annee_scolaire', 'niveau__ordre', 'libelle'],
            },
        ),
    ]
