# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='students.eleve', verbose_name='élève'),
        ),
    ]
