# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_saisis', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finance.fraisscolarite', verbose_name='frais concernés'),
        ),
    ]
