# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date_inscription', models.DateField(blank=True, null=True, verbose_name="date d'inscription")),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Année validée'), ('TRANSFERE', 'Transféré'), ('ABANDON', 'Abandon')], default='EN_COURS', max_length=15, verbose_name='statut')),
                ('observation', models.TextField(blank=True, verbose_name='observation')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-annee_scolaire__libelle', 'eleve__nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True, verbose_name='matricule')),
                ('prenom', models.CharField(max_length=60, verbose_name='prénom')),
                ('nom', models.CharField(max_length=60, verbose_name='nom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/', verbose_name='photo')),
                ('contact_urgence', models.CharField(blank=True, max_length=100, verbose_name="contact d'urgence")),
                ('infos_medicales', models.TextField(blank=True, verbose_name='informations médicales')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='academic.classe', verbose_name='classe')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
