# Generated by Django 5.2.17 on 2026-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="nom de l'établissement")),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='slogan / devise')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissement/', verbose_name='logo')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='adresse e-mail')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
                ('description', models.TextField(blank=True, verbose_name='présentation')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
            },
        ),
    ]
