# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('libelle', models.CharField(max_length=9, unique=True, verbose_name='libellé')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('active', models.BooleanField(default=False, verbose_name='année en cours')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, verbose_name='coefficient')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['classe', 'matiere'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='libellé')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('couleur', models.CharField(blank=True, default='#2563eb', max_length=7, verbose_name='couleur (hexadécimal)')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('cycle', models.CharField(choices=[('MATERNELLE', 'Maternelle'), ('ELEMENTAIRE', 'Élémentaire (Primaire)'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=20, verbose_name='cycle')),
                ('libelle', models.CharField(max_length=60, verbose_name='libellé')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'niveau',
                'verbose_name_plural': 'niveaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(choices=[('T1', '1er trimestre'), ('T2', '2e trimestre'), ('T3', '3e trimestre'), ('S1', '1er semestre'), ('S2', '2e semestre')], max_length=2, verbose_name='code')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('active', models.BooleanField(default=False, verbose_name='période en cours')),
            ],
            options={
                'verbose_name': 'période',
                'verbose_name_plural': 'périodes',
                'ordering': ['annee_scolaire', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='salle')),
            ],
            options={
                'verbose_name': 'séance (emploi du temps)',
                'verbose_name_plural': 'séances (emploi du temps)',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('libelle', models.CharField(max_length=60, verbose_name='libellé')),
                ('capacite', models.PositiveSmallIntegerField(default=30, verbose_name="capacité d'accueil")),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='salle')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academic.anneescolaire', verbose_name='année scolaire')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['niveau__ordre', 'libelle'],
            },
        ),
    ]
