# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ENSEIGNANT', 'DIRECTEUR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='professeur principal'),
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.classe', verbose_name='classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academic.matiere', verbose_name='matière'),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('cycle', 'code'), name='niveau_unique_par_cycle'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academic.niveau', verbose_name='niveau'),
        ),
        migrations.AddField(
            model_name='periode',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='academic.anneescolaire', verbose_name='année scolaire'),
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='academic.cours', verbose_name='cours'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('classe', 'matiere'), name='cours_unique_par_classe'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('libelle', 'annee_scolaire'), name='classe_unique_par_annee'),
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('annee_scolaire', 'code'), name='periode_unique_par_annee'),
        ),
    ]
