# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, help_text="Laisser vide si l'élève était absent.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='note obtenue')),
                ('observation', models.CharField(blank=True, max_length=150, verbose_name='observation')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['evaluation', 'eleve'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('INTERROGATION', 'Interrogation'), ('PRATIQUE', 'Évaluation pratique')], default='DEVOIR', max_length=15, verbose_name='type')),
                ('date', models.DateField(verbose_name="date de l'évaluation")),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='note maximale')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.cours', verbose_name='cours')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.periode', verbose_name='période')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-date'],
            },
        ),
    ]
