# Generated by Django 5.2.17 on 2026-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('cible', models.CharField(choices=[('TOUS', 'Tout le monde'), ('ENSEIGNANTS', 'Enseignants'), ('PARENTS', 'Parents'), ('ELEVES', 'Élèves')], default='TOUS', max_length=15, verbose_name='destinataires')),
                ('importante', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-date_publication', '-cree_le'],
            },
        ),
    ]
