# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date', models.DateField(verbose_name='date')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('EXCUSE', 'Absence excusée')], default='PRESENT', max_length=10, verbose_name='statut')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif / justification')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='academic.cours', verbose_name='cours')),
            ],
            options={
                'verbose_name': 'présence',
                'verbose_name_plural': 'présences',
                'ordering': ['-date', 'eleve__nom'],
            },
        ),
    ]
